/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPancakeV2Router02,
  IPancakeV2Router02Interface,
} from "../../../contracts/interfaces/IPancakeV2Router02";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amountTokenDesired",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amountTokenMin",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amountETHMin",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "deadline",
        type: "uint256",
      },
    ],
    name: "addLiquidityETH",
    outputs: [
      {
        internalType: "uint256",
        name: "amountToken",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amountETH",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "liquidity",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IPancakeV2Router02__factory {
  static readonly abi = _abi;
  static createInterface(): IPancakeV2Router02Interface {
    return new Interface(_abi) as IPancakeV2Router02Interface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPancakeV2Router02 {
    return new Contract(address, _abi, runner) as unknown as IPancakeV2Router02;
  }
}
