/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICoinrushFactory,
  ICoinrushFactoryInterface,
} from "../../../contracts/BondingCurvePool.sol/ICoinrushFactory";

const _abi = [
  {
    inputs: [],
    name: "platformTradeFeeBps",
    outputs: [
      {
        internalType: "uint16",
        name: "",
        type: "uint16",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "treasury",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ICoinrushFactory__factory {
  static readonly abi = _abi;
  static createInterface(): ICoinrushFactoryInterface {
    return new Interface(_abi) as ICoinrushFactoryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ICoinrushFactory {
    return new Contract(address, _abi, runner) as unknown as ICoinrushFactory;
  }
}
